# Copyright 2015-2019 Meik Michalke <meik.michalke@hhu.de>
#
# This file is part of the R package tm.plugin.koRpus.
#
# tm.plugin.koRpus is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# tm.plugin.koRpus is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with tm.plugin.koRpus.  If not, see <http://www.gnu.org/licenses/>.

#' Getter/setter methods for kRp.flatHier objects
#' 
#' These methods should be used to get or set values of text objects
#' generated by functions like \code{\link[tm.plugin.koRpus:readCorpus]{readCorpus}}.
#' 
#' \itemize{
#'   \item{\code{taggedText()} }{returns the \code{TT.res} slot.}
#'   \item{\code{describe()} }{returns the \code{desc} slot.}
#'   \item{\code{corpusReadability()} }{returns the list of \code{kRp.readability} objects.}
#'   \item{\code{corpusTm()} }{returns the \code{VCorpus} object.}
#'   \item{\code{corpusMeta()} }{returns the list with meta information.}
#'   \item{\code{corpusHyphen()} }{returns the list of \code{kRp.hyphen} objects.}
#'   \item{\code{corpusTTR()} }{returns the list of \code{kRp.TTR} objects.}
#'   \item{\code{corpusFiles()} }{returns the character vector of file names of the object.}
#'   \item{\code{[}/\code{[[} }{can be used as a shortcut to index the results of \code{corpusSummary()}.}
#'   \item{\code{tif_as_corpus_df} }{returns the whole corpus in a single TIF[1] compliant
#'      data.frame.}
#'   \item{\code{tif_as_tokens_df} }{returns the \code{TT.res} slots of all texts in a single TIF[1] compliant
#'      data.frame, i.e., \code{doc_id} is not a factor but a character vector.}
#' }
#' 
#' Please note that the \code{<-} methods usually do not work on nested levels but only on single object nodes.
#' 
#' @param obj An object of class \code{\link[tm.plugin.koRpus:kRp.flatHier-class]{kRp.flatHier}}.
#' @param level Either the integer value or name (character string) of the target level. If \code{NULL} the top level is used.
#' @param id Character value specifying the category ID of child objects you want to get.
#'    If \code{NULL} then the child objects of the current top level are returned,
#'    otherwise all children with the ID specified. Only interpreted if \code{level=NULL}
#'    (you can't use both at the same time).
#' @rdname kRp.flatHier_get-methods
#' @docType methods
#' @references
#'    [1] Text Interchange Formats (\url{https://github.com/ropensci/tif})
#' @export
#' @importFrom koRpus taggedText
#' @aliases
#'    taggedText,-methods
#'    taggedText,kRp.flatHier-method
#' @include 01_class_01_kRp.flatHier.R
#' @examples
#' \dontrun{
#' taggedText(myCorpus)
#' corpusMeta(myCorpus, "note") <- "an interesting read!"
#' 
#' # export object to TIF compliant data frame
#' myCorpus_df <- tif_as_corpus_df(myCorpus)
#' }
## the standard generic for taggedText() is defined in the koRpus package
setMethod("taggedText",
  signature=signature(obj="kRp.flatHier"),
  function (obj){
    return(slot(obj, name="TT.res"))
  }
)

## the standard generic for taggedText()<- is defined in the koRpus package
#' @rdname kRp.flatHier_get-methods
#' @importFrom koRpus taggedText<-
#' @export
#' @docType methods
#' @aliases
#'    taggedText<-,-methods
#'    taggedText<-,kRp.flatHier-method
#' @include 01_class_01_kRp.flatHier.R
setMethod("taggedText<-",
  signature=signature(obj="kRp.flatHier"),
  function (obj, value){
    slot(obj, name="TT.res") <- value
    return(obj)
  }
)

## the standard generic for describe() is defined in the sylly package
#' @rdname kRp.flatHier_get-methods
#' @importFrom sylly describe
#' @docType methods
#' @export
#' @aliases
#'    describe,-methods
#'    describe,kRp.flatHier-method
#' @include 01_class_01_kRp.flatHier.R
setMethod("describe",
  signature=signature(obj="kRp.flatHier"),
  function (obj){
    return(slot(obj, name="desc"))
  }
)

## the standard generic for describe()<- is defined in the sylly package
#' @rdname kRp.flatHier_get-methods
#' @importFrom sylly describe<-
#' @export
#' @docType methods
#' @aliases
#'    describe<-,-methods
#'    describe<-,kRp.flatHier-method
#' @include 01_class_01_kRp.flatHier.R
setMethod("describe<-",
  signature=signature(obj="kRp.flatHier"),
  function (obj, value){
    slot(obj, name="desc") <- value
    return(obj)
  }
)

## the standard generic for language() is defined in the sylly package
#' @importFrom sylly language
#' @rdname kRp.flatHier-methods
#' @export
#' @docType methods
#' @aliases
#'    language,-methods
#'    language,kRp.flatHier-method
#' @include 01_class_01_kRp.flatHier.R
setMethod("language",
  signature=signature(obj="kRp.flatHier"),
  function (obj){
    result <- slot(obj, name="lang")
    return(result)
  }
)

## the standard generic for language()<- is defined in the sylly package
#' @importFrom sylly language<-
#' @rdname kRp.flatHier-methods
#' @export
#' @docType methods
#' @aliases
#'    language<-,-methods
#'    language<-,kRp.flatHier-method
#' @include 01_class_01_kRp.flatHier.R
setMethod("language<-",
  signature=signature(obj="kRp.flatHier"),
  function (obj, value){
    slot(obj, name="lang") <- value
    return(obj)
  }
)


#' @rdname kRp.flatHier_get-methods
#' @docType methods
#' @export
setGeneric("corpusReadability", function(obj) standardGeneric("corpusReadability"))
#' @rdname kRp.flatHier_get-methods
#' @docType methods
#' @export
#' @aliases
#'    corpusReadability,-methods
#'    corpusReadability,kRp.flatHier-method
#' @include 01_class_01_kRp.flatHier.R
setMethod("corpusReadability",
  signature=signature(obj="kRp.flatHier"),
  function (obj){
    return(slot(obj, name="readability"))
  }
)

#' @rdname kRp.flatHier_get-methods
#' @export
#' @docType methods
# @param value The new value to replace the current with.
setGeneric("corpusReadability<-", function(obj, value) standardGeneric("corpusReadability<-"))
#' @rdname kRp.flatHier_get-methods
#' @export
#' @docType methods
#' @aliases
#'    corpusReadability<-,-methods
#'    corpusReadability<-,kRp.flatHier-method
#' @include 01_class_01_kRp.flatHier.R
setMethod("corpusReadability<-",
  signature=signature(obj="kRp.flatHier"),
  function (obj, value){
    slot(obj, name="readability") <- value
    return(obj)
  }
)


#' @rdname kRp.flatHier_get-methods
#' @docType methods
#' @export
setGeneric("corpusTm", function(obj, id=NULL) standardGeneric("corpusTm"))
#' @rdname kRp.flatHier_get-methods
#' @docType methods
#' @export
#' @aliases
#'    corpusTm,-methods
#'    corpusTm,kRp.flatHier-method
#' @include 01_class_01_kRp.flatHier.R
setMethod("corpusTm",
  signature=signature(obj="kRp.flatHier"),
  function (obj){
    return(slot(obj, name="raw")[["tm"]])
  }
)

#' @rdname kRp.flatHier_get-methods
#' @export
#' @docType methods
# @param value The new value to replace the current with.
setGeneric("corpusTm<-", function(obj, value) standardGeneric("corpusTm<-"))
#' @rdname kRp.flatHier_get-methods
#' @export
#' @docType methods
#' @aliases
#'    corpusTm<-,-methods
#'    corpusTm<-,kRp.flatHier-method
#' @include 01_class_01_kRp.flatHier.R
setMethod("corpusTm<-",
  signature=signature(obj="kRp.flatHier"),
  function (obj, value){
    slot(obj, name="raw")[["tm"]] <- value
    return(obj)
  }
)

#' @rdname kRp.flatHier_get-methods
#' @param meta If not NULL, the \code{meta} list entry of the given name.
#' @param fail Logical, whether the method should fail with an error if \code{meta} was not found.
#'    If set to \code{FALSE}, returns \code{invisible(NULL)} instead.
#' @docType methods
#' @export
setGeneric("corpusMeta", function(obj, meta=NULL, fail=TRUE) standardGeneric("corpusMeta"))
#' @rdname kRp.flatHier_get-methods
#' @docType methods
#' @export
#' @aliases
#'    corpusMeta,-methods
#'    corpusMeta,kRp.flatHier-method
#' @include 01_class_01_kRp.flatHier.R
setMethod("corpusMeta",
  signature=signature(obj="kRp.flatHier"),
  function (obj, meta=NULL, fail=TRUE){
    all.meta <- slot(obj, name="meta")
    if(is.null(meta)){
      result <- all.meta
    } else {
      if(meta %in% names(all.meta)){
        result <- all.meta[[meta]]
      } else {
        if(isTRUE(fail)){
          stop(simpleError(paste0("Entry named \"", meta,"\" not found in the slot \"meta\" of this object!")))
        } else {
          result <- invisible(NULL)
        }
      }
    }

    return(result)
  }
)


#' @rdname kRp.flatHier_get-methods
#' @export
#' @docType methods
# @param value The new value to replace the current with.
setGeneric("corpusMeta<-", function(obj, meta=NULL, value) standardGeneric("corpusMeta<-"))
#' @rdname kRp.flatHier_get-methods
#' @export
#' @docType methods
#' @aliases
#'    corpusMeta<-,-methods
#'    corpusMeta<-,kRp.flatHier-method
#' @include 01_class_01_kRp.flatHier.R
setMethod("corpusMeta<-",
  signature=signature(obj="kRp.flatHier"),
  function (obj, meta=NULL, value){
    if(is.null(meta)){
      slot(obj, name="meta") <- value
    } else {
      slot(obj, name="meta")[[meta]] <- value
    }
    return(obj)
  }
)

#' @rdname kRp.flatHier_get-methods
#' @docType methods
#' @export
setGeneric("corpusHyphen", function(obj) standardGeneric("corpusHyphen"))
#' @rdname kRp.flatHier_get-methods
#' @docType methods
#' @export
#' @aliases
#'    corpusHyphen,-methods
#'    corpusHyphen,kRp.flatHier-method
#' @include 01_class_01_kRp.flatHier.R
setMethod("corpusHyphen",
  signature=signature(obj="kRp.flatHier"),
  function (obj){
    return(slot(obj, name="hyphen"))
  }
)

#' @rdname kRp.flatHier_get-methods
#' @export
#' @docType methods
# @param value The new value to replace the current with.
setGeneric("corpusHyphen<-", function(obj, value) standardGeneric("corpusHyphen<-"))
#' @rdname kRp.flatHier_get-methods
#' @export
#' @docType methods
#' @aliases
#'    corpusHyphen<-,-methods
#'    corpusHyphen<-,kRp.flatHier-method
#' @include 01_class_01_kRp.flatHier.R
setMethod("corpusHyphen<-",
  signature=signature(obj="kRp.flatHier"),
  function (obj, value){
    slot(obj, name="hyphen") <- value
    return(obj)
  }
)

#' @rdname kRp.flatHier_get-methods
#' @docType methods
#' @export
setGeneric("corpusTTR", function(obj) standardGeneric("corpusTTR"))
#' @rdname kRp.flatHier_get-methods
#' @docType methods
#' @export
#' @aliases
#'    corpusTTR,-methods
#'    corpusTTR,kRp.flatHier-method
#' @include 01_class_01_kRp.flatHier.R
setMethod("corpusTTR",
  signature=signature(obj="kRp.flatHier"),
  function (obj){
    return(slot(obj, name="TTR"))
  }
)


#' @rdname kRp.flatHier_get-methods
#' @export
#' @docType methods
# @param value The new value to replace the current with.
setGeneric("corpusTTR<-", function(obj, value) standardGeneric("corpusTTR<-"))
#' @rdname kRp.flatHier_get-methods
#' @export
#' @docType methods
#' @aliases
#'    corpusTTR<-,-methods
#'    corpusTTR<-,kRp.flatHier-method
#' @include 01_class_01_kRp.flatHier.R
setMethod("corpusTTR<-",
  signature=signature(obj="kRp.flatHier"),
  function (obj, value){
    slot(obj, name="TTR") <- value
    return(obj)
  }
)


#' @rdname kRp.flatHier_get-methods
#' @docType methods
#' @export
setGeneric("corpusFreq", function(obj) standardGeneric("corpusFreq"))
#' @rdname kRp.flatHier_get-methods
#' @docType methods
#' @export
#' @aliases
#'    corpusFreq,-methods
#'    corpusFreq,kRp.flatHier-method
#' @include 01_class_01_kRp.flatHier.R
setMethod("corpusFreq",
  signature=signature(obj="kRp.flatHier"),
  function (obj){
    return(slot(obj, name="freq"))
  }
)


#' @rdname kRp.flatHier_get-methods
#' @export
#' @docType methods
# @param value The new value to replace the current with.
setGeneric("corpusFreq<-", function(obj, value) standardGeneric("corpusFreq<-"))
#' @rdname kRp.flatHier_get-methods
#' @export
#' @docType methods
#' @aliases
#'    corpusFreq<-,-methods
#'    corpusFreq<-,kRp.flatHier-method
#' @include 01_class_01_kRp.flatHier.R
setMethod("corpusFreq<-",
  signature=signature(obj="kRp.flatHier"),
  function (obj, value){
    slot(obj, name="freq") <- value
    return(obj)
  }
)

#' @rdname kRp.flatHier_get-methods
#' @docType methods
#' @param paths Logical, indicates for \code{corpusFiles()} whether full paths should be returned, or just the actual file name.
#' @export
setGeneric("corpusFiles", function(obj, paths=FALSE, ...) standardGeneric("corpusFiles"))
#' @rdname kRp.flatHier_get-methods
#' @docType methods
#' @export
#' @aliases
#'    corpusFiles,-methods
#'    corpusFiles,kRp.flatHier-method
#' @include 01_class_01_kRp.flatHier.R
setMethod("corpusFiles",
  signature=signature(obj="kRp.flatHier"),
  function (obj, paths=FALSE){
    if(isTRUE(paths)){
      result <- apply(
        meta(corpusTm(obj))[, c("path","file")],
        1,
        paste0,
        collapse=.Platform$file.sep
      )
    } else {
      result <- as.character(meta(corpusTm(obj))[["file"]])
    }
    result <- as.character(result)
    names(result) <- NULL
    return(result)
  }
)

#' @rdname kRp.flatHier_get-methods
#' @export
#' @docType methods
# @param value The new value to replace the current with.
setGeneric("corpusFiles<-", function(obj, value) standardGeneric("corpusFiles<-"))
#' @rdname kRp.flatHier_get-methods
#' @export
#' @docType methods
#' @aliases
#'    corpusFiles<-,-methods
#'    corpusFiles<-,kRp.flatHier-method
#' @include 01_class_01_kRp.flatHier.R
setMethod("corpusFiles<-",
  signature=signature(obj="kRp.flatHier"),
  function (obj, value){
    meta(corpusTm(obj))[["file"]] <- value
    return(obj)
  }
)

#' @rdname kRp.flatHier_get-methods
#' @export
#' @include 01_class_01_kRp.flatHier.R
is.corpus <- function(obj){
  inherits(obj, "kRp.flatHier")
}

#' @rdname kRp.flatHier_get-methods
#' @param x See \code{obj}.
#' @param i Defines the row selector (\code{[}) or the name to match (\code{[[}) in the summary slot.
#' @param j Defines the column selector in the summary slot.
#' @export
#' @docType methods
#' @aliases
#'    [,-methods
#'    [,kRp.flatHier,ANY,ANY,ANY-method
setMethod("[",
  signature=signature(x="kRp.flatHier"),
  function (x, i, j){
    return(corpusSummary(x)[i, j])
  }
)

#' @rdname kRp.flatHier_get-methods
#' @export
#' @docType methods
#' @aliases
#'    [<-,-methods
#'    [<-,kRp.flatHier,ANY,ANY,ANY-method
setMethod("[<-",
  signature=signature(x="kRp.flatHier"),
  function (x, i, j, value){
    corpusSummary(x)[i, j] <- value
    return(x)
  }
)

#' @rdname kRp.flatHier_get-methods
#' @export
#' @docType methods
#' @aliases
#'    [[,-methods
#'    [[,kRp.flatHier,ANY-method
setMethod("[[",
  signature=signature(x="kRp.flatHier"),
  function (x, i){
    return(corpusSummary(x)[[i]])
  }
)

#' @rdname kRp.flatHier_get-methods
#' @export
#' @docType methods
#' @aliases
#'    [[<-,-methods
#'    [[<-,kRp.flatHier,ANY,ANY-method
setMethod("[[<-",
  signature=signature(x="kRp.flatHier"),
  function (x, i, value){
    corpusSummary(x)[[i]] <- value
    return(x)
  }
)

#' @rdname kRp.flatHier_get-methods
#' @param tokens An object of class \code{kRp.flatHier}.
#' @docType methods
#' @export
setGeneric("tif_as_tokens_df", function(tokens) standardGeneric("tif_as_tokens_df"))
#' @rdname kRp.flatHier_get-methods
#' @export
#' @docType methods
#' @aliases
#'    tif_as_tokens_df,-methods
#'    tif_as_tokens_df,hierarchy-method
setMethod("tif_as_tokens_df",
  signature=signature(tokens="kRp.flatHier"),
  function(tokens){
    result <- taggedText(tokens)
    # TIF needs doc_id to be a character vector, not a factor
    result[["doc_id"]] <- as.character(result[["doc_id"]])
    return(result)
  }
)

#' @rdname kRp.flatHier_get-methods
#' @param corpus An object of class \code{kRp.flatHier}.
#' @docType methods
#' @export
setGeneric("tif_as_corpus_df", function(corpus) standardGeneric("tif_as_corpus_df"))
#' @rdname kRp.flatHier_get-methods
#' @importFrom NLP meta
#' @export
#' @docType methods
#' @aliases
#'    tif_as_corpus_df,-methods
#'    tif_as_corpus_df,hierarchy-method
setMethod("tif_as_corpus_df",
  signature=signature(corpus="kRp.flatHier"),
  function(corpus){
    corpus_tm <- corpusTm(obj=corpus)
    corpus_texts <- sapply(corpus_tm, function(thisText){paste0(thisText, collapse="\n")})
    corpus_meta <- meta(corpus_tm)
    result <- data.frame(
      doc_id=as.character(corpus_meta[["doc_id"]]),
      text=as.character(corpus_texts),
      stringsAsFactors=FALSE
    )
    extra_cols <- !colnames(corpus_meta) %in% "doc_id"
    if(sum(extra_cols) > 1){
      # append hierarchy information
      result <- cbind(result, as.data.frame(corpus_meta)[,extra_cols])
    } else {}
    rownames(result) <- NULL
    return(result)
  }
)

