# Copyright 2015-2019 Meik Michalke <meik.michalke@hhu.de>
#
# This file is part of the R package tm.plugin.koRpus.
#
# tm.plugin.koRpus is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# tm.plugin.koRpus is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with tm.plugin.koRpus.  If not, see <http://www.gnu.org/licenses/>.

#' Getter/setter methods for kRp.hierarchy objects
#' 
#' These methods should be used to get or set values of text objects
#' generated by functions like \code{\link[tm.plugin.koRpus:readCorpus]{readCorpus}}.
#' 
#' \itemize{
#'   \item{\code{corpusTagged()} }{returns the list of \code{kRp.tagged} objects.}
#'   \item{\code{corpusReadability()} }{returns the list of \code{kRp.readability} objects.}
#'   \item{\code{corpusTm()} }{returns the \code{VCorpus} object.}
#'   \item{\code{corpusMeta()} }{returns the list with meta information.}
#'   \item{\code{corpusHyphen()} }{returns the list of \code{kRp.hyphen} objects.}
#'   \item{\code{corpusTTR()} }{returns the list of \code{kRp.TTR} objects.}
#'   \item{\code{corpusLevel()} }{returns the level value of the top level object.}
#'   \item{\code{corpusCategory()} }{returns the character vector of categories of the top level object.}
#'   \item{\code{corpusID()} }{returns the character vector of category IDs of the top level object.}
#'   \item{\code{corpusPath()} }{returns the root directory path of the top level object.}
#'   \item{\code{corpusFiles()} }{returns the character vector of file names of level 0 of the object.}
#'   \item{\code{[}/\code{[[} }{can be used as a shortcut to index the results of \code{corpusSummary()}.}
#'   \item{\code{tif_as_corpus_df} }{returns the whole corpus in a single TIF[1] compliant
#'      data.frame.}
#'   \item{\code{tif_as_tokens_df} }{returns the \code{TT.res} slots of all texts in a single TIF[1] compliant
#'      data.frame, i.e., \code{doc_id} is not a factor but a character vector.}
#' }
#' 
#' Please note that the \code{<-} methods usually do not work on nested levels but only on single object nodes.
#' 
#' @param obj An object of class \code{\link[tm.plugin.koRpus:kRp.hierarchy-class]{kRp.hierarchy}}.
#' @param level Either the integer value or name (character string) of the target level. If \code{NULL} the top level is used.
#' @param id Character value specifying the category ID of child objects you want to get.
#'    If \code{NULL} then the child objects of the current top level are returned,
#'    otherwise all children with the ID specified. Only interpreted if \code{level=NULL}
#'    (you can't use both at the same time).
#' @rdname kRp.hierarchy_get-methods
#' @docType methods
#' @references
#'    [1] Text Interchange Formats (\url{https://github.com/ropensci/tif})
#' @export
#' @examples
#' \dontrun{
#' corpusTagged(myCorpus)
#' corpusMeta(myCorpus, "note") <- "an interesting read!"
#' 
#' # export object to TIF compliant data frame
#' myCorpus_df <- tif_as_corpus_df(myCorpus)
#' }
setGeneric("corpusTagged", function(obj, level=NULL, id=NULL) standardGeneric("corpusTagged"))
#' @rdname kRp.hierarchy_get-methods
#' @docType methods
#' @export
#' @aliases
#'    corpusTagged,-methods
#'    corpusTagged,kRp.hierarchy-method
#' @include 01_class_01_kRp.hierarchy.R
setMethod("corpusTagged",
  signature=signature(obj="kRp.hierarchy"),
  function (obj, level=NULL, id=NULL){
    if(all(is.null(level), is.null(id))){
      result <- slot(obj, name="tagged")
    } else {
      result <- unlist(lapply(corpusChildren(obj, level=level, id=id), slot, name="tagged"))
    }
    return(result)
  }
)

#' @rdname kRp.hierarchy_get-methods
#' @export
#' @docType methods
#' @param value The new value to replace the current with.
setGeneric("corpusTagged<-", function(obj, value) standardGeneric("corpusTagged<-"))
#' @rdname kRp.hierarchy_get-methods
#' @export
#' @docType methods
#' @aliases
#'    corpusTagged<-,-methods
#'    corpusTagged<-,kRp.hierarchy-method
#' @include 01_class_01_kRp.hierarchy.R
setMethod("corpusTagged<-",
  signature=signature(obj="kRp.hierarchy"),
  function (obj, value){
    slot(obj, name="tagged") <- value
    return(obj)
  }
)

#' @rdname kRp.hierarchy_get-methods
#' @docType methods
#' @export
setGeneric("corpusReadability", function(obj, level=NULL, id=NULL) standardGeneric("corpusReadability"))
#' @rdname kRp.hierarchy_get-methods
#' @docType methods
#' @export
#' @aliases
#'    corpusReadability,-methods
#'    corpusReadability,kRp.hierarchy-method
#' @include 01_class_01_kRp.hierarchy.R
setMethod("corpusReadability",
  signature=signature(obj="kRp.hierarchy"),
  function (obj, level=NULL, id=NULL){
#     result <- unlist(lapply(corpusChildren(obj, level=0), slot, name="readability"))
    if(all(is.null(level), is.null(id))){
      result <- slot(obj, name="readability")
    } else {
      result <- unlist(lapply(corpusChildren(obj, level=level, id=id), slot, name="readability"))
    }
    return(result)
  }
)

#' @rdname kRp.hierarchy_get-methods
#' @export
#' @docType methods
# @param value The new value to replace the current with.
setGeneric("corpusReadability<-", function(obj, value) standardGeneric("corpusReadability<-"))
#' @rdname kRp.hierarchy_get-methods
#' @export
#' @docType methods
#' @aliases
#'    corpusReadability<-,-methods
#'    corpusReadability<-,kRp.hierarchy-method
#' @include 01_class_01_kRp.hierarchy.R
setMethod("corpusReadability<-",
  signature=signature(obj="kRp.hierarchy"),
  function (obj, value){
    slot(obj, name="readability") <- value
    return(obj)
  }
)


#' @rdname kRp.hierarchy_get-methods
#' @docType methods
#' @export
setGeneric("corpusTm", function(obj, id=NULL) standardGeneric("corpusTm"))
#' @rdname kRp.hierarchy_get-methods
#' @docType methods
#' @export
#' @aliases
#'    corpusTm,-methods
#'    corpusTm,kRp.hierarchy-method
#' @include 01_class_01_kRp.hierarchy.R
setMethod("corpusTm",
  signature=signature(obj="kRp.hierarchy"),
  function (obj, id=NULL){
    if(corpusLevel(obj) > 0){
      corpus_part <- corpusChildren(obj, level=NULL, id=id)
      corpus_part <- unlist(lapply(corpus_part, function(thisPart){
        if(corpusLevel(thisPart) > 0){
          return(corpusChildren(thisPart, level=0, id=NULL))
        } else {
          return(thisPart)
        }
      }))
      tm_list <- lapply(corpus_part, function(thisObj) {
        return(slot(thisObj, name="raw")[["tm"]])
      })
      if(length(tm_list) > 1){
        result <- tm_list[[1]]
        for (this_tm_num in 2:length(tm_list)){
          result <- c(result, tm_list[[this_tm_num]])
        }
      } else {
        result <- tm_list
      }
    } else {
      result <- slot(obj, name="raw")[["tm"]]
    }
    return(result)
  }
)

#' @rdname kRp.hierarchy_get-methods
#' @export
#' @docType methods
# @param value The new value to replace the current with.
setGeneric("corpusTm<-", function(obj, value) standardGeneric("corpusTm<-"))
#' @rdname kRp.hierarchy_get-methods
#' @export
#' @docType methods
#' @aliases
#'    corpusTm<-,-methods
#'    corpusTm<-,kRp.hierarchy-method
#' @include 01_class_01_kRp.hierarchy.R
setMethod("corpusTm<-",
  signature=signature(obj="kRp.hierarchy"),
  function (obj, value){
    slot(obj, name="raw")[["tm"]] <- value
    return(obj)
  }
)

#' @rdname kRp.hierarchy_get-methods
#' @param meta If not NULL, the \code{meta} list entry of the given name.
#' @param fail Logical, whether the method should fail with an error if \code{meta} was not found.
#'    If set to \code{FALSE}, returns \code{invisible(NULL)} instead.
#' @docType methods
#' @export
setGeneric("corpusMeta", function(obj, meta=NULL, fail=TRUE) standardGeneric("corpusMeta"))
#' @rdname kRp.hierarchy_get-methods
#' @docType methods
#' @export
#' @aliases
#'    corpusMeta,-methods
#'    corpusMeta,kRp.hierarchy-method
#' @include 01_class_01_kRp.hierarchy.R
setMethod("corpusMeta",
  signature=signature(obj="kRp.hierarchy"),
  function (obj, meta=NULL, fail=TRUE){
    all.meta <- slot(obj, name="meta")
    if(is.null(meta)){
      result <- all.meta
    } else {
      if(meta %in% names(all.meta)){
        result <- all.meta[[meta]]
      } else {
        if(isTRUE(fail)){
          stop(simpleError(paste0("Entry named \"", meta,"\" not found in the slot \"meta\" of this object!")))
        } else {
          result <- invisible(NULL)
        }
      }
    }

    return(result)
  }
)


#' @rdname kRp.hierarchy_get-methods
#' @export
#' @docType methods
# @param value The new value to replace the current with.
setGeneric("corpusMeta<-", function(obj, meta=NULL, value) standardGeneric("corpusMeta<-"))
#' @rdname kRp.hierarchy_get-methods
#' @export
#' @docType methods
#' @aliases
#'    corpusMeta<-,-methods
#'    corpusMeta<-,kRp.hierarchy-method
#' @include 01_class_01_kRp.hierarchy.R
setMethod("corpusMeta<-",
  signature=signature(obj="kRp.hierarchy"),
  function (obj, meta=NULL, value){
    if(is.null(meta)){
      slot(obj, name="meta") <- value
    } else {
      slot(obj, name="meta")[[meta]] <- value
    }
    return(obj)
  }
)

#' @rdname kRp.hierarchy_get-methods
#' @docType methods
#' @export
setGeneric("corpusHyphen", function(obj, level=NULL, id=NULL) standardGeneric("corpusHyphen"))
#' @rdname kRp.hierarchy_get-methods
#' @docType methods
#' @export
#' @aliases
#'    corpusHyphen,-methods
#'    corpusHyphen,kRp.hierarchy-method
#' @include 01_class_01_kRp.hierarchy.R
setMethod("corpusHyphen",
  signature=signature(obj="kRp.hierarchy"),
  function (obj, level=NULL, id=NULL){
    if(all(is.null(level), is.null(id))){
      result <- slot(obj, name="hyphen")
    } else {
      result <- unlist(lapply(corpusChildren(obj, level=level, id=id), slot, name="hyphen"))
    }
    return(result)
  }
)

#' @rdname kRp.hierarchy_get-methods
#' @export
#' @docType methods
# @param value The new value to replace the current with.
setGeneric("corpusHyphen<-", function(obj, value) standardGeneric("corpusHyphen<-"))
#' @rdname kRp.hierarchy_get-methods
#' @export
#' @docType methods
#' @aliases
#'    corpusHyphen<-,-methods
#'    corpusHyphen<-,kRp.hierarchy-method
#' @include 01_class_01_kRp.hierarchy.R
setMethod("corpusHyphen<-",
  signature=signature(obj="kRp.hierarchy"),
  function (obj, value){
    slot(obj, name="hyphen") <- value
    return(obj)
  }
)

#' @rdname kRp.hierarchy_get-methods
#' @docType methods
#' @export
setGeneric("corpusTTR", function(obj, level=NULL, id=NULL) standardGeneric("corpusTTR"))
#' @rdname kRp.hierarchy_get-methods
#' @docType methods
#' @export
#' @aliases
#'    corpusTTR,-methods
#'    corpusTTR,kRp.hierarchy-method
#' @include 01_class_01_kRp.hierarchy.R
setMethod("corpusTTR",
  signature=signature(obj="kRp.hierarchy"),
  function (obj, level=NULL, id=NULL){
    if(all(is.null(level), is.null(id))){
      result <- slot(obj, name="TTR")
    } else {
      result <- unlist(lapply(corpusChildren(obj, level=level, id=id), slot, name="TTR"))
    }
    return(result)
  }
)


#' @rdname kRp.hierarchy_get-methods
#' @export
#' @docType methods
# @param value The new value to replace the current with.
setGeneric("corpusTTR<-", function(obj, value) standardGeneric("corpusTTR<-"))
#' @rdname kRp.hierarchy_get-methods
#' @export
#' @docType methods
#' @aliases
#'    corpusTTR<-,-methods
#'    corpusTTR<-,kRp.hierarchy-method
#' @include 01_class_01_kRp.hierarchy.R
setMethod("corpusTTR<-",
  signature=signature(obj="kRp.hierarchy"),
  function (obj, value){
    slot(obj, name="TTR") <- value
    return(obj)
  }
)


#' @rdname kRp.hierarchy_get-methods
#' @docType methods
#' @export
setGeneric("corpusFreq", function(obj, level=NULL, id=NULL) standardGeneric("corpusFreq"))
#' @rdname kRp.hierarchy_get-methods
#' @docType methods
#' @export
#' @aliases
#'    corpusFreq,-methods
#'    corpusFreq,kRp.hierarchy-method
#' @include 01_class_01_kRp.hierarchy.R
setMethod("corpusFreq",
  signature=signature(obj="kRp.hierarchy"),
  function (obj, level=NULL, id=NULL){
    if(all(is.null(level), is.null(id))){
      result <- slot(obj, name="freq")
    } else {
      result <- unlist(lapply(corpusChildren(obj, level=level, id=id), slot, name="freq"))
    }
    return(result)
  }
)


#' @rdname kRp.hierarchy_get-methods
#' @export
#' @docType methods
# @param value The new value to replace the current with.
setGeneric("corpusFreq<-", function(obj, value) standardGeneric("corpusFreq<-"))
#' @rdname kRp.hierarchy_get-methods
#' @export
#' @docType methods
#' @aliases
#'    corpusFreq<-,-methods
#'    corpusFreq<-,kRp.hierarchy-method
#' @include 01_class_01_kRp.hierarchy.R
setMethod("corpusFreq<-",
  signature=signature(obj="kRp.hierarchy"),
  function (obj, value){
    slot(obj, name="freq") <- value
    return(obj)
  }
)

#' @rdname kRp.hierarchy_get-methods
#' @docType methods
#' @export
setGeneric("corpusLevel", function(obj) standardGeneric("corpusLevel"))
#' @rdname kRp.hierarchy_get-methods
#' @docType methods
#' @export
#' @aliases
#'    corpusLevel,-methods
#'    corpusLevel,kRp.hierarchy-method
#' @include 01_class_01_kRp.hierarchy.R
setMethod("corpusLevel",
  signature=signature(obj="kRp.hierarchy"),
  function (obj){
    result <- slot(obj, name="level")
    return(result)
  }
)

#' @rdname kRp.hierarchy_get-methods
#' @export
#' @docType methods
# @param value The new value to replace the current with.
setGeneric("corpusLevel<-", function(obj, value) standardGeneric("corpusLevel<-"))
#' @rdname kRp.hierarchy_get-methods
#' @export
#' @docType methods
#' @aliases
#'    corpusLevel<-,-methods
#'    corpusLevel<-,kRp.hierarchy-method
#' @include 01_class_01_kRp.hierarchy.R
setMethod("corpusLevel<-",
  signature=signature(obj="kRp.hierarchy"),
  function (obj, value){
    slot(obj, name="level") <- value
    return(obj)
  }
)

#' @rdname kRp.hierarchy_get-methods
#' @docType methods
#' @export
setGeneric("corpusChildren", function(obj, level=NULL, id=NULL) standardGeneric("corpusChildren"))
#' @rdname kRp.hierarchy_get-methods
#' @docType methods
#' @export
#' @aliases
#'    corpusChildren,-methods
#'    corpusChildren,kRp.hierarchy-method
#' @include 01_class_01_kRp.hierarchy.R
setMethod("corpusChildren",
  signature=signature(obj="kRp.hierarchy"),
  function (obj, level=NULL, id=NULL){
    child_obj <- slot(obj, name="children")
    obj_hier <- corpusMeta(obj)[["hierarchy"]]
    if(!is.null(level)){
      if(is.character(level)){
        if(!level %in% names(obj_hier)){
          stop(simpleError("Requested \"level\" does not exist in given object!"))
        } else {}
        num_level <- length(obj_hier) - which(names(obj_hier) %in% level)
        if(length(num_level) > 1){
          stop(simpleError("Requested \"level\" was found on multiple times in the given object! I'm confused!"))
        } else {}
        child_obj <- corpusChildren(obj, level=num_level)
     } else if(is.numeric(level)){
        obj_level <- corpusLevel(obj)
        if(obj_level < level){
          stop(simpleError("The value for \"level\" can't be greater than the object's top level!"))
        } else if(obj_level > level){
          child_obj <- slot(obj, name="children")
          while(level < (obj_level - 1)){
            child_obj <- unlist(lapply(child_obj, corpusChildren))
            obj_level <- obj_level - 1
          }
        } else {}
      } else {
        stop(simpleError("Invalid value for \"level\" given, must be numeric or character!"))
      }
    } else if(!is.null(id)){
      if(!is.character(id)){
        stop(simpleError("Invalid value for \"id\" given, must be character!"))
      } else {}
      if(!id %in% unlist(obj_hier)){
        stop(simpleError("Requested \"id\" does not exist in given object!"))
      } else {}
      # find the level we need
      id_in_hier <- which(sapply(obj_hier, function(this_hier){id %in% this_hier}))
      if(length(id_in_hier) > 1){
        stop(simpleError("Requested \"id\" was found on multiple levels in the given object! I'm confused!"))
      } else {}
      id_in_level <- length(obj_hier) - id_in_hier
      child_obj_level <- corpusChildren(obj, level=id_in_level)
      id_in_child <- which(sapply(child_obj_level, function(this_child){corpusID(this_child) %in% id}))
      child_obj <- child_obj_level[id_in_child]
    } else {}
    return(child_obj)
  }
)

#' @rdname kRp.hierarchy_get-methods
#' @export
#' @docType methods
# @param value The new value to replace the current with.
setGeneric("corpusChildren<-", function(obj, value) standardGeneric("corpusChildren<-"))
#' @rdname kRp.hierarchy_get-methods
#' @export
#' @docType methods
#' @aliases
#'    corpusChildren<-,-methods
#'    corpusChildren<-,kRp.hierarchy-method
#' @include 01_class_01_kRp.hierarchy.R
setMethod("corpusChildren<-",
  signature=signature(obj="kRp.hierarchy"),
  function (obj, value){
    slot(obj, name="children") <- value
    return(obj)
  }
)

#' @rdname kRp.hierarchy_get-methods
#' @docType methods
#' @export
setGeneric("corpusCategory", function(obj, level=NULL, id=NULL) standardGeneric("corpusCategory"))
#' @rdname kRp.hierarchy_get-methods
#' @docType methods
#' @export
#' @aliases
#'    corpusCategory,-methods
#'    corpusCategory,kRp.hierarchy-method
#' @include 01_class_01_kRp.hierarchy.R
setMethod("corpusCategory",
  signature=signature(obj="kRp.hierarchy"),
  function (obj, level=NULL, id=NULL){
    if(all(is.null(level), is.null(id))){
      result <- slot(obj, name="category")
    } else {
      result <- unlist(lapply(corpusChildren(obj, level=level, id=id), slot, name="category"))
    }
    return(result)
  }
)

#' @rdname kRp.hierarchy_get-methods
#' @export
#' @docType methods
# @param value The new value to replace the current with.
setGeneric("corpusCategory<-", function(obj, value) standardGeneric("corpusCategory<-"))
#' @rdname kRp.hierarchy_get-methods
#' @export
#' @docType methods
#' @aliases
#'    corpusCategory<-,-methods
#'    corpusCategory<-,kRp.hierarchy-method
#' @include 01_class_01_kRp.hierarchy.R
setMethod("corpusCategory<-",
  signature=signature(obj="kRp.hierarchy"),
  function (obj, value){
    slot(obj, name="category") <- value
    return(obj)
  }
)

#' @rdname kRp.hierarchy_get-methods
#' @docType methods
#' @export
setGeneric("corpusID", function(obj, level=NULL) standardGeneric("corpusID"))
#' @rdname kRp.hierarchy_get-methods
#' @docType methods
#' @export
#' @aliases
#'    corpusID,-methods
#'    corpusID,kRp.hierarchy-method
#' @include 01_class_01_kRp.hierarchy.R
setMethod("corpusID",
  signature=signature(obj="kRp.hierarchy"),
  function (obj, level=NULL){
    if(is.null(level)){
      result <- slot(obj, name="id")
    } else {
      result <- unlist(lapply(corpusChildren(obj, level=level), slot, name="id"))
    }
    return(result)
  }
)

#' @rdname kRp.hierarchy_get-methods
#' @export
#' @docType methods
# @param value The new value to replace the current with.
setGeneric("corpusID<-", function(obj, value) standardGeneric("corpusID<-"))
#' @rdname kRp.hierarchy_get-methods
#' @export
#' @docType methods
#' @aliases
#'    corpusID<-,-methods
#'    corpusID<-,kRp.hierarchy-method
#' @include 01_class_01_kRp.hierarchy.R
setMethod("corpusID<-",
  signature=signature(obj="kRp.hierarchy"),
  function (obj, value){
    slot(obj, name="id") <- value
    return(obj)
  }
)

#' @rdname kRp.hierarchy_get-methods
#' @docType methods
#' @export
setGeneric("corpusPath", function(obj, level=NULL) standardGeneric("corpusPath"))
#' @rdname kRp.hierarchy_get-methods
#' @docType methods
#' @export
#' @aliases
#'    corpusPath,-methods
#'    corpusPath,kRp.hierarchy-method
#' @include 01_class_01_kRp.hierarchy.R
setMethod("corpusPath",
  signature=signature(obj="kRp.hierarchy"),
  function (obj, level=NULL){
    if(is.null(level)){
      result <- slot(obj, name="path")
    } else {
      result <- unlist(lapply(corpusChildren(obj, level=level), slot, name="path"))
    }
    return(result)
  }
)

#' @rdname kRp.hierarchy_get-methods
#' @export
#' @docType methods
# @param value The new value to replace the current with.
setGeneric("corpusPath<-", function(obj, value) standardGeneric("corpusPath<-"))
#' @rdname kRp.hierarchy_get-methods
#' @export
#' @docType methods
#' @aliases
#'    corpusPath<-,-methods
#'    corpusPath<-,kRp.hierarchy-method
#' @include 01_class_01_kRp.hierarchy.R
setMethod("corpusPath<-",
  signature=signature(obj="kRp.hierarchy"),
  function (obj, value){
    slot(obj, name="path") <- value
    return(obj)
  }
)

#' @rdname kRp.hierarchy_get-methods
#' @docType methods
#' @param paths Logical, indicates for \code{corpusFiles()} whether full paths should be returned, or just the actual file name.
#' @export
setGeneric("corpusFiles", function(obj, level=0, id=NULL, paths=FALSE) standardGeneric("corpusFiles"))
#' @rdname kRp.hierarchy_get-methods
#' @docType methods
#' @export
#' @aliases
#'    corpusFiles,-methods
#'    corpusFiles,kRp.hierarchy-method
#' @include 01_class_01_kRp.hierarchy.R
setMethod("corpusFiles",
  signature=signature(obj="kRp.hierarchy"),
  function (obj, level=0, id=NULL, paths=FALSE){
    if(corpusLevel(obj) > 0){
      # make sure 'id' becomes effective at all, it's ignored by corpusChildren() if level is set
      if(!is.null(id)){
        level <- NULL
      } else {}
      if(all(is.null(level), is.null(id))){
        result <- unlist(slot(obj, name="files"))
        if(isTRUE(paths)){
          result <- file.path(slot(obj, name="path"), result)
        }
      } else {
        result <- unlist(sapply(
          corpusChildren(obj, level=level, id=id),
          function(thisChild){
            if(corpusLevel(thisChild) > 0){
              return(sapply(corpusChildren(thisChild, level=0), corpusFiles, level=NULL, id=NULL, paths=paths))
            } else {
              return(corpusFiles(thisChild, level=NULL, id=NULL, paths=paths))
            }
          }
        ))
      }
    } else {
      result <- unlist(slot(obj, name="files"))
    }
    result <- as.vector(result)
    names(result) <- NULL
    return(result)
  }
)

#' @rdname kRp.hierarchy_get-methods
#' @export
#' @docType methods
# @param value The new value to replace the current with.
setGeneric("corpusFiles<-", function(obj, value) standardGeneric("corpusFiles<-"))
#' @rdname kRp.hierarchy_get-methods
#' @export
#' @docType methods
#' @aliases
#'    corpusFiles<-,-methods
#'    corpusFiles<-,kRp.hierarchy-method
#' @include 01_class_01_kRp.hierarchy.R
setMethod("corpusFiles<-",
  signature=signature(obj="kRp.hierarchy"),
  function (obj, value){
    slot(obj, name="files") <- value
    return(obj)
  }
)

#' @rdname kRp.hierarchy_get-methods
#' @export
#' @include 01_class_01_kRp.hierarchy.R
is.corpus <- function(obj){
  inherits(obj, "kRp.hierarchy")
}

#' @rdname kRp.hierarchy_get-methods
#' @param x See \code{obj}.
#' @param i Defines the row selector (\code{[}) or the name to match (\code{[[}) in the summary slot.
#' @param j Defines the column selector in the summary slot.
#' @export
#' @docType methods
#' @aliases
#'    [,-methods
#'    [,kRp.hierarchy,ANY,ANY,ANY-method
setMethod("[",
  signature=signature(x="kRp.hierarchy"),
  function (x, i, j){
    return(corpusSummary(x)[i, j])
  }
)

#' @rdname kRp.hierarchy_get-methods
#' @export
#' @docType methods
#' @aliases
#'    [<-,-methods
#'    [<-,kRp.hierarchy,ANY,ANY,ANY-method
setMethod("[<-",
  signature=signature(x="kRp.hierarchy"),
  function (x, i, j, value){
    corpusSummary(x)[i, j] <- value
    return(x)
  }
)

#' @rdname kRp.hierarchy_get-methods
#' @export
#' @docType methods
#' @aliases
#'    [[,-methods
#'    [[,kRp.hierarchy,ANY-method
setMethod("[[",
  signature=signature(x="kRp.hierarchy"),
  function (x, i){
    return(corpusSummary(x)[[i]])
  }
)

#' @rdname kRp.hierarchy_get-methods
#' @export
#' @docType methods
#' @aliases
#'    [[<-,-methods
#'    [[<-,kRp.hierarchy,ANY,ANY-method
setMethod("[[<-",
  signature=signature(x="kRp.hierarchy"),
  function (x, i, value){
    corpusSummary(x)[[i]] <- value
    return(x)
  }
)

#' @rdname kRp.hierarchy_get-methods
#' @param tokens An object of class \code{kRp.hierarchy}.
#' @docType methods
#' @export
setGeneric("tif_as_tokens_df", function(tokens) standardGeneric("tif_as_tokens_df"))
#' @rdname kRp.hierarchy_get-methods
#' @export
#' @docType methods
#' @aliases
#'    tif_as_tokens_df,-methods
#'    tif_as_tokens_df,hierarchy-method
setMethod("tif_as_tokens_df",
  signature=signature(tokens="kRp.hierarchy"),
  function(tokens){
    bottom_level <- corpusTagged(tokens, level=0)
    result <- do.call(rbind.data.frame, lapply(bottom_level, tif_as_tokens_df))
    rownames(result) <- NULL
    return(result)
  }
)

#' @rdname kRp.hierarchy_get-methods
#' @param corpus An object of class \code{kRp.hierarchy}.
#' @docType methods
#' @export
setGeneric("tif_as_corpus_df", function(corpus) standardGeneric("tif_as_corpus_df"))
#' @rdname kRp.hierarchy_get-methods
#' @importFrom NLP meta
#' @export
#' @docType methods
#' @aliases
#'    tif_as_corpus_df,-methods
#'    tif_as_corpus_df,hierarchy-method
setMethod("tif_as_corpus_df",
  signature=signature(corpus="kRp.hierarchy"),
  function(corpus){
    corpus_tm <- corpusTm(obj=corpus)
    corpus_texts <- sapply(corpus_tm, function(thisText){paste0(thisText, collapse="\n")})
    corpus_files <- corpusFiles(corpus)
    corpus_meta <- meta(corpus_tm)
    result <- data.frame(
      doc_id=as.character(corpus_meta[["textID"]]),
      text=as.character(corpus_texts),
      stringsAsFactors=FALSE
    )
    extra_cols <- !colnames(corpus_meta) %in% "textID"
    if(sum(extra_cols) > 1){
      # append hierarchy information
      result <- cbind(result, as.data.frame(corpus_meta)[,extra_cols])
    } else {}
    rownames(result) <- NULL
    return(result)
  }
)

